### ISSUE TITLE
建议添加数字选项

### ISSUE THREAD

**Issue by Nriver** [find456789/pipyuan#1]
我是会去记那么多参数是哪家的源。不如输个命令把各个源按123456列出来，再输入数字直接切换。

**Comment by find456789** [comment]
可能是我文档没有写好， 不用记忆参数，  那些字母 都是各家公司的第一个汉字的 第一个拼音的第一个字母

比如：

`pipyuan a   `

这里面的 `a` ， 就是 阿里云 > **a**liyun(阿里云 的拼音) -> a(拼音的第一个字母)



再比如：

`pipyuan q `

这里面的 `q` ， 就是 清华大学 > **q**inghuadaxue(清华大学 的拼音) ->q(拼音的第一个字母)

这样就比较好记忆了
-----

举例：

我想改成 `豆瓣` 的源， 拼音 `douban` 的第一个字母是 `d `， 那我就执行 `pipyuan d`

我想改成 `腾讯` 的源， 拼音 `tengxun` 的第一个字母是 `t `， 那我就执行 `pipyuan t`


-----

短期内，可能不会增加数字选项， 因为目前拼音首字母 可能更好记忆一些， 了解了其中的规律， 就没有记忆负担了


---

谢谢支持

**Comment by find456789** [comment]
你好， 我已在 readme.md 里， 更新了关于 字母参数的 记忆技巧、说明，   所以先关闭这个 issue了， 感谢你的支持
