### ISSUE TITLE
本地装了Python3.9.2，运行的时候调用了Python2.7的版本

### ISSUE THREAD

**Issue by PPP1G** [find456789/pipyuan#2]
安装用了`pip3 install pipyuan`
运行`pipyuan a`

```你选择了:  阿里云 https://mirrors.aliyun.com/pypi/simple/
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pip-21.0.1-py2.7.egg/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/Library/Python/2.7/site-packages/pip-21.0.1-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/pip-21.0.1-py2.7.egg/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/Library/Python/2.7/site-packages/pip-21.0.1-py2.7.egg/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
未知指令！ 请检查后再输入
```

macOS 12.0.1 (21A559)
Python 3.9.2

**Comment by find456789** [comment]
谢谢， 确实个bug ， 我会在稍后修复

**Comment by find456789** [comment]
方便给出下 ：

 ` python --version` 返回的信息吗

**Comment by PPP1G** [comment]
> 方便给出下 ：
> 
> ` python --version` 返回的信息吗

`$ python --version && pip --version`

```
Python 3.9.2
pip 21.3.1 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
```

**Comment by find456789** [comment]
pipyuan 内部是调用   `python -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple`  来修改源的

你的环境，Python默认指向了 3.9.2  ,    Python版本和pip版本也都没有错

 

请问 `pip3 --version`  的返回 和   `pip --version`  一样吗， 方便贴出来吗 

谢谢

**Comment by PPP1G** [comment]
> pipyuan 内部是调用 `python -m pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple` 来修改源的
> 
> 你的环境，Python默认指向了 3.9.2 , Python版本和pip版本也都没有错
> 
> 请问 `pip3 --version` 的返回 和 `pip --version` 一样吗， 方便贴出来吗
> 
> 谢谢

![image](https://user-images.githubusercontent.com/56902719/139627207-3a20a8bf-bfd7-4d37-8c96-c8ea6539713a.png)

**Comment by find456789** [comment]
谢谢， 这个情况有点复杂，我不知道问题出在哪里

你方便 克隆 代码到本地， 测试一下吗  
克隆到本地， 进入 src 目录 ，执行  `python main.py a`    看看能不能工作

**Comment by PPP1G** [comment]
> python main.py a

依然无法解决问题
![image](https://user-images.githubusercontent.com/56902719/139646797-83e35492-89f2-4655-9ab3-2ee23ddb9480.png)

**Comment by find456789** [comment]
谢谢

请问  `python -m pip --version`  返回的是什么

**Comment by PPP1G** [comment]
> 谢谢
> 
> 请问 `python -m pip --version` 返回的是什么

![image](https://user-images.githubusercontent.com/56902719/139775665-8c696f6c-b871-4624-b30e-af59acb98211.png)

**Comment by find456789** [comment]
谢谢
说实话，哥， 这个bug 我没弄明白，暂时不知道咋解决

不知道 你是否方便， 通过源码、单步调试， 看能否找出问题所在

**Comment by PPP1G** [comment]
> 谢谢 说实话，哥， 这个bug 我没弄明白，暂时不知道咋解决
> 
> 不知道 你是否方便， 通过源码、单步调试， 看能否找出问题所在

![image](https://user-images.githubusercontent.com/56902719/139784004-ac8413ca-9f86-4587-8bdb-69d417e1a3e6.png)
在虚机上重新测了一下正常使用，可能是我本地Mac的python路径设定有问题，这个应该不算bug，我自己排查一下本地环境

**Comment by find456789** [comment]
@PPP1G 

 恭喜！

如果方便的话，麻烦你把排查后的原因  分享到这个issue里， 这样，其他朋友遇到类似问题， 可能会得到灵感

谢谢
